---
name: Release

on:
  workflow_run:
    types:
      - completed
    workflows:
      - "ci"
    branches:
      - release/*
jobs:
  get-tag:
    name: Get tag
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      tag: ${{ steps.get-tag-step.outputs.tag }}
    steps:
      - name: Get tag
        run: |
          branch=${{github.event.workflow_run.head_branch}}
          echo tag=${branch#release/} >> $GITHUB_OUTPUT
        id: get-tag-step

  create-release:
    needs: get-tag
    uses: networkservicemesh/.github/.github/workflows/release.yaml@main
    secrets:
      token: ${{ secrets.BOT_TOKEN }}

  release-dependent-repositories:
    name: Update cmd-dashboard-ui repository
    runs-on: ubuntu-latest
    needs: get-tag
    steps:
      - name: Checkout bszirtes/cmd-dashboard-ui repository
        uses: actions/checkout@v4
        with:
          path: bszirtes/cmd-dashboard-ui
          repository: bszirtes/cmd-dashboard-ui
          token: ${{ secrets.BOT_TOKEN }}

      - name: Push branch to the cmd-dashboard-ui
        working-directory: bszirtes/cmd-dashboard-ui
        run: |
          echo Starting to release repository cmd-backend-ui
          git checkout -b ${{ github.event.workflow_run.head_branch }}
          git push -f origin ${{ github.event.workflow_run.head_branch }}
